export default function Sustainability() {
  return (
    <section
      className="py-24 bg-gradient-to-b from-white to-green-50"
    >
      <div className="max-w-7xl mx-auto px-6">

        <h2 className="text-5xl font-bold text-center text-slate-900 mb-6">
          Sustainable by Design
        </h2>

        <p className="text-center text-slate-600 max-w-4xl mx-auto mb-16">
          DSAINT combines energy-efficient infrastructure,
          municipal integration and distributed computing
          to create a more sustainable approach to sovereign AI.
        </p>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">

          {/* BTES */}
          <div className="bg-white rounded-3xl shadow-lg border border-green-100 p-8">
            <h3 className="text-2xl font-bold text-green-700 mb-4">
              BTES Thermal Storage
            </h3>

            <p className="text-slate-700 leading-relaxed">
              Borehole Thermal Energy Storage enables
              long-term thermal management and supports
              efficient use of excess heat generated by
              AI infrastructure.
            </p>
          </div>

          {/* Heat Recovery */}
          <div className="bg-white rounded-3xl shadow-lg border border-green-100 p-8">
            <h3 className="text-2xl font-bold text-green-700 mb-4">
              Heat Recovery
            </h3>

            <p className="text-slate-700 leading-relaxed">
              Waste heat from AI infrastructure can be
              redirected to support municipal facilities,
              public buildings and future district heating
              applications.
            </p>
          </div>

          {/* Energy Efficiency */}
          <div className="bg-white rounded-3xl shadow-lg border border-green-100 p-8">
            <h3 className="text-2xl font-bold text-green-700 mb-4">
              Energy Efficiency
            </h3>

            <p className="text-slate-700 leading-relaxed">
              Direct-to-chip liquid cooling, modern power
              systems and optimized infrastructure design
              target a PUE of ≤ 1.20 across the DSAINT
              Core Infrastructure Network.
            </p>
          </div>

          {/* Municipal Integration */}
          <div className="bg-white rounded-3xl shadow-lg border border-green-100 p-8">
            <h3 className="text-2xl font-bold text-green-700 mb-4">
              Municipal Integration
            </h3>

            <p className="text-slate-700 leading-relaxed">
              DSAINT infrastructure is designed to become
              part of local communities, creating economic,
              educational and technological value for
              municipalities across Germany.
            </p>
          </div>

        </div>

        {/* Sustainability Vision */}
        <div className="mt-16 bg-white rounded-3xl shadow-xl border border-green-100 p-10">

          <h3 className="text-3xl font-bold text-center text-green-700 mb-6">
            Sustainable AI Through Distribution
          </h3>

          <p className="text-slate-700 text-center max-w-5xl mx-auto leading-relaxed">
            DSAINT combines environmentally friendly Core
            Infrastructure Nodes with a Community Compute
            Federation of Citizen AI Nodes.
            <br />
            <br />
            By distributing compute-intensive workloads across
            a trusted network of participants, DSAINT improves
            infrastructure utilization, reduces waste and
            enables a more sustainable model for the future
            development of artificial intelligence.
          </p>

        </div>

      </div>
    </section>
  );
}
